info:
  name: Update Config
  type: http
  seq: 2

http:
  method: PATCH
  url: http://localhost:8000/admin/config
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "PREEMPTION_POLICY": "footprint",
        "RESUME_MODE": "recompute"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
